conditioning:
  method: ps
  params:
    scale: 0.3

dpsconditioning:
  method: ps
  params:
    scale: 1.0

tmpdconditioning:
  method: tmp

pigdmconditioning:
  method: pig

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  noise:
    name: gaussian
    sigma: 0.05
