---
attention_type: ddpm
attn_resolutions: [16]
beta_max: 20
beta_min: 0.1
ch_mult: [1, 2, 2, 2]
conditional: true
conv_size: 3
dropout: 0.1
ema_rate: 0.999
embedding_type: positional
fir: true
fir_kernel: [1, 3, 3, 1]
init_scale: 0
name: ncsnpp
nf: 128
nonlinearity: swish
normalization: group_norm
num_res_blocks: 4
num_scales: 1000
progressive: none
progressive_combine: sum
progressive_input: residual
resamp_with_conv: true
resblock_type: biggan
scale_by_sigma: true
sigma_max: 90
sigma_min: 0.01
skip_rescale: true