---
attention_type: ddpm
attn_resolutions: [16]
ch_mult: [1, 2, 4, 8, 16, 32, 32, 32]
conditional: true
conv_size: 3
dropout: 0
ema_rate: 0.9999
embedding_type: fourier
fir: true
fir_kernel: [1, 3, 3, 1]
fourier_scale: 16
init_scale: 0
name: ncsnpp
nf: 16
nonlinearity: swish
normalization: group_norm
num_res_blocks: 1
num_scales: 2000
progressive: output_skip
progressive_combine: sum
progressive_input: input_skip
resamp_with_conv: true
resblock_type: biggan
scale_by_sigma: true
sigma_max: 1348
sigma_min: 0.01
skip_rescale: true